### PR TITLE
Switched to AutoML for generalisation 

### PR DESCRIPTION
**Pull request by IronistM**
This pull request uses the `Getting_started_with_Forecast.ipynb` so no new data in this case

*Description of changes:*

- Fixed typo (`versionId`)
- Updated gitignore
- Switched to AutoML for generalisation : I think that it would be best to use the `Auto ML` for scratching the surface of the Forecast service.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by chrisking** [comment]
Thanks for the commit, could you add something to the notebooks to visualize the performance of the models?

**Comment by chrisking** [comment]
Actually @IronistM after thinking about it, could you create a second notebook that explores the AutoML piece like you did in the original base notebook, then graph the results of each model? Also then revert the original notebook just to MQRNN. That has served well for a simple intro, your option with multiple models would be great for a more advanced audience, thus a different notebook to educate them.

**Comment by akhilrazdan** [comment]
I agree with chrisking@ Thanks for this, but for the default notebook, it's better to have one of the algorithms as compared to starting out the demo with the autoML notebook. It's more time consuming and a relatively complex use case to onboard with.

**Comment by IronistM** [comment]
Cool! I thought that most people will start with the AutoML. Thinking it again, I guess that this would be true in the case of using the UI of the service but this might not be the case when using the SDK.

**Comment by chrisking** [comment]
@IronistM it looks like you still have the predictor name 

`predictorName = project+'_auto_ml'` set as that in the original file, could you put it back to the previous value?

**Comment by chrisking** [comment]
@IronistM  other notebook looks great!

**Comment by chrisking** [comment]
@akhilrazdan this looks good to ship to me.

**Comment by IronistM** [comment]
@chrisking @akhilrazdan I added a pandas dataframe to preview error rates and (mean) prediction.

**Comment by chrisking** [comment]
@akhilrazdan looks ready to ship now. Please merge.

**Pull request merged**
